import './style.css';
type Row = Record<string, any>;
const app = document.querySelector<HTMLDivElement>('#app')!;
let access = '', refresh = '', page = 'Dashboard', busy = false;
let base = localStorage.getItem('rizio_api') || '/v1';
let refreshWork: Promise<void> | undefined;
const esc = (v: unknown) => String(v ?? 'â€”').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function api(path: string, method = 'GET', body?: unknown, retry = true): Promise<any> {
  const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(access ? { Authorization: `Bearer ${access}` } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  if (response.status === 401 && refresh && retry) {
    refreshWork ??= api('/auth/refresh', 'POST', {refresh_token: refresh}, false).then(d => {access=d.access_token; refresh=d.refresh_token;}).finally(()=>{refreshWork=undefined;});
    try { await refreshWork; } catch(e) {access='';refresh='';login();throw e;}
    return api(path, method, body, false);
  }
  const result = await response.json();
  if (!response.ok || result.status === 'error') throw new Error(result.message || 'Permintaan gagal');
  return result.data;
}
function notice(message: string, error=false) { const target=document.querySelector('#notice'); if(target) {target.className=`notice ${error?'error':''}`;target.textContent=message;} }
function data(form: HTMLFormElement): Row { return Object.fromEntries(new FormData(form).entries()); }
function login() {
 app.innerHTML=`<section class="card login"><h1>RizIO<span style="color:#299d89">.</span></h1><p>Ruang kendali administrator</p><form id="login"><label>Alamat API<input name="base" value="${esc(base)}" required></label><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Kata sandi<input name="password" type="password" autocomplete="current-password" required></label><button>Masuk</button></form><div id="notice" role="status"></div><p class="muted">Sesi disimpan di memori dan berakhir saat tab ditutup.</p></section>`;
 document.querySelector<HTMLFormElement>('form')!.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;const d=data(f);base=String(d.base).replace(/\/$/,'');if(!base.startsWith('/')&&!base.startsWith('https://')&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/v1$/.test(base)){notice('Gunakan URL HTTPS atau /v1.',true);return;}localStorage.setItem('rizio_api',base);const button=f.querySelector('button')!;button.disabled=true;try{const r=await api('/auth/login','POST',{email:d.email,password:d.password});if(r.user.role!=='admin')throw new Error('Akun administrator diperlukan.');access=r.access_token;refresh=r.refresh_token;await render();}catch(e){notice(String(e),true);button.disabled=false;}};
}
const pages=['Dashboard','Pengguna','Perangkat','Online','Offline','Firmware','OTA','Perintah','Log','Sistem'];
function rows(value:any):Row[]{return Array.isArray(value)?value:value?.items||value?.devices||value?.users||value?.firmwares||value?.commands||value?.logs||[];}
function table(items:Row[],columns:string[],action?:(r:Row)=>string):string{return items.length?`<div class="table"><table><thead><tr>${columns.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join('')}${action?'<th>Tindakan</th>':''}</tr></thead><tbody>${items.map(r=>`<tr>${columns.map(c=>`<td>${esc(typeof r[c]==='object'?JSON.stringify(r[c]):r[c])}</td>`).join('')}${action?`<td>${action(r)}</td>`:''}</tr>`).join('')}</tbody></table></div>`:'<p>Belum ada data.</p>';}
async function render(){
 app.innerHTML=`<div class="shell"><aside><h2>RizIO.</h2><nav>${pages.map(p=>`<button data-page="${p}" class="${p===page?'active':''}">${p}</button>`).join('')}</nav></aside><main><header><div><div class="muted">ADMINISTRATOR / RIZIO CLOUD</div><h1>${page}</h1></div><div class="toolbar"><button id="reload" class="secondary">Perbarui</button><button id="logout" class="secondary">Keluar</button></div></header><div id="notice" role="status"></div><section id="content" aria-live="polite"><p>Memuat dataâ€¦</p></section></main></div>`;
 document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page!;void render();});
 document.querySelector<HTMLButtonElement>('#reload')!.onclick=()=>void render();
 document.querySelector<HTMLButtonElement>('#logout')!.onclick=async()=>{try{await api('/auth/logout','POST',{refresh_token:refresh});}catch{}access='';refresh='';login();};
 const currentPage=page;const content=document.querySelector('#content')!;
 try {
  if(page==='Dashboard') {const s=await api('/admin/summary');content.innerHTML=`<div class="stats">${Object.entries(s).filter(([,v])=>typeof v!=='object').map(([k,v])=>`<div class="card stat"><span class="muted">${esc(k.replaceAll('_',' '))}</span><strong>${esc(v)}</strong></div>`).join('')}</div><div class="card"><h2>Distribusi firmware & koneksi</h2><pre>${esc(JSON.stringify(s,null,2))}</pre></div>`;}
  else if(page==='Pengguna')content.innerHTML=`<div class="card">${table(rows(await api('/admin/users')),['id','name','email','role','status','created_at'])}</div>`;
  else if(['Perangkat','Online','Offline'].includes(page)) {let devices=rows(await api('/admin/devices'));if(page==='Online')devices=devices.filter(d=>d.online);if(page==='Offline')devices=devices.filter(d=>!d.online);content.innerHTML=`<div class="card">${table(devices,['sn','name','model','firmware_version','owner_user_id','online','disabled','last_seen'],r=>`<button data-info="${esc(r.sn)}" class="secondary">Telemetri</button> <button data-disable="${esc(r.sn)}" data-value="${!r.disabled}">${r.disabled?'Aktifkan':'Nonaktifkan'}</button>`)}</div>`;document.querySelectorAll<HTMLButtonElement>('[data-disable]').forEach(b=>b.onclick=()=>act(async()=>{if(!confirm(`${b.textContent} ${b.dataset.disable}?`))return;await api('/admin/devices/'+encodeURIComponent(b.dataset.disable!),'PATCH',{disabled:b.dataset.value==='true'});await render();}));document.querySelectorAll<HTMLButtonElement>('[data-info]').forEach(b=>b.onclick=()=>{const device=devices.find(d=>d.sn===b.dataset.info);const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>Telemetri ${esc(device?.sn)}</h2><pre>${esc(JSON.stringify(device,null,2))}</pre><button>Tutup</button>`;document.body.append(dialog);dialog.querySelector('button')!.onclick=()=>dialog.remove();dialog.showModal();});}
  else if(page==='Firmware') {content.innerHTML=`<div class="card"><h2>Daftarkan firmware</h2><form id="firmware"><div class="grid">${['model','hardware_version','version','url','checksum','file_size'].map(n=>`<label>${n}<input name="${n}" required ${n==='file_size'?'type="number" min="1"':n==='url'?'type="url"':''}></label>`).join('')}</div><label>Catatan rilis<textarea name="release_notes"></textarea></label><button>Daftarkan</button></form><p class="muted">Unggah binary ke hosting HTTPS Anda, lalu masukkan URL dan SHA256. Pilih file untuk menghitung checksum dan ukuran.</p><input id="binary" type="file" accept=".bin"><button id="upload">Unggah binary ke server</button></div><div class="card">${table(rows(await api('/admin/firmwares')),['id','model','hardware_version','version','file_size','is_active'])}</div>`;document.querySelector<HTMLInputElement>('#binary')!.onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());(document.querySelector('[name="checksum"]') as HTMLInputElement).value=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');(document.querySelector('[name="file_size"]') as HTMLInputElement).value=String(file.size);};document.querySelector<HTMLButtonElement>('#upload')!.onclick=()=>act(async()=>{const f=document.querySelector<HTMLFormElement>('#firmware')!;const binary=document.querySelector<HTMLInputElement>('#binary')!.files?.[0];if(!binary)throw new Error('Pilih file binary terlebih dahulu.');const body=new FormData();body.set('file',binary);for(const key of ['model','hardware_version','version','release_notes'])body.set(key,String(data(f)[key]||''));const r=await fetch(base+'/admin/firmwares/upload',{method:'POST',headers:{Authorization:'Bearer '+access},body});const result=await r.json();if(!r.ok)throw new Error(result.message||'Upload gagal');await render();notice('Binary firmware tersimpan.');});document.querySelector<HTMLFormElement>('#firmware')!.onsubmit=e=>{e.preventDefault();const d=data(e.currentTarget as HTMLFormElement);act(async()=>{await api('/admin/firmwares','POST',{...d,file_size:Number(d.file_size)});await render();notice('Metadata firmware disimpan.');});};}
  else if(page==='OTA') {const [ds,fs]=await Promise.all([api('/admin/devices'),api('/admin/firmwares')]);content.innerHTML=`<div class="card"><h2>Deployment firmware</h2><form id="ota"><label>Perangkat<select name="sn">${rows(ds).map(d=>`<option value="${esc(d.sn)}">${esc(d.name||d.sn)} Â· ${esc(d.model)} / ${esc(d.hardware_version)}</option>`).join('')}</select></label><label>Firmware<select name="firmware_id">${rows(fs).map(f=>`<option value="${esc(f.id)}">${esc(f.model)} / ${esc(f.hardware_version)} Â· ${esc(f.version)}</option>`).join('')}</select></label><button>Kirim OTA</button></form><p class="muted">Pantau ACK pada menu Perintah dan versi perangkat sesudah restart.</p></div>`;document.querySelector<HTMLFormElement>('#ota')!.onsubmit=e=>{e.preventDefault();const d=data(e.currentTarget as HTMLFormElement);act(async()=>{if(!confirm('Kirim pembaruan firmware ke perangkat ini?'))return;const r=await api('/admin/devices/'+encodeURIComponent(d.sn)+'/ota','POST',{firmware_id:d.firmware_id});notice(`OTA diantrikan. ID: ${r.request_id}. Menunggu konfirmasi perangkat.`);});};}
  else if(page==='Perintah')content.innerHTML=`<div class="card">${table(rows(await api('/admin/commands')),['request_id','sn','command','command_status','created_at','ack_at'])}</div>`;
  else if(page==='Log')content.innerHTML=`<div class="card">${table(rows(await api('/admin/logs')),['sn','event_type','payload','created_at'])}</div>`;
  else {const r=await fetch(base.replace(/\/v1$/,'')+'/health');content.innerHTML=`<div class="card"><h2>Kesehatan layanan</h2><pre>${esc(JSON.stringify(await r.json(),null,2))}</pre></div>`;}
 }catch(e){if(currentPage===page) {content.innerHTML='<div class="card"><p>Data tidak dapat dimuat. Gunakan Perbarui untuk mencoba kembali.</p></div>';notice(String(e),true);}}
}
async function act(work:()=>Promise<void>){if(busy)return;busy=true;document.querySelectorAll<HTMLButtonElement>('main button').forEach(b=>b.disabled=true);try{await work();}catch(e){notice(String(e),true);}finally{busy=false;document.querySelectorAll<HTMLButtonElement>('main button').forEach(b=>b.disabled=false);}}
login();


