#pragma once
#include "platform.h"
struct Channel { int pin; bool activeLow; bool state; };
extern DynamicJsonDocument identity;
extern Channel channels[16];
extern size_t channelCount;
extern SecureClient tls;
extern PubSubClient mqtt;
extern WebServerType web;
extern bool provisioning;
extern uint32_t restartAt;
extern uint32_t localBusyUntil;
String jsonText(JsonVariantConst value);
String topic(const char *suffix);
bool loadIdentity();
bool saveWifi(const String &ssid, const String &password);
void resetLocal();
void beginWifi();
void tickWifi();
void configureTls(SecureClient &client);
void beginGpio();
void beginSchedules();
void tickSchedules();
bool syncSchedules(JsonObjectConst input);
bool applyScheduledScene(JsonObjectConst input);
void beginTemperatureSensor();
void tickTemperatureSensor();
void addTemperatureState(JsonObject state);
void addState(JsonObject state);
bool setGpio(int pin, bool state);
bool verifyToken(const String &token);
void loadLocalAccess();
bool saveLocalAccess(const String &key);
void clearLocalAccess();
String localAccessKey();
String issueLocalChallenge();
bool verifyLocalRequest(const String &authorization, const String &method, const String &path, const String &body);
bool constantEqual(const String &a, const String &b);
void beginWeb();
void beginDiscovery();
void tickDiscovery();
void beginMqtt();
void tickMqtt();
void publishState();
String executeCommand(JsonObjectConst input, bool local);
bool installOta(JsonObjectConst command, String &error);
